version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: lab-discussion
    volumes:
      - mongodb_data:/data/db
    networks:
      - lab-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://db:27017/lab-discussion
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - lab-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 80:80
    networks:
      - lab-network

volumes:
  mongodb_data:

networks:
  lab-network:
    driver: bridge
