version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
      - ./backend/src/database/migrations:/app/dist/database/migrations
    depends_on:
      - postgres
    command: /bin/sh -c "npm run build && npx knex migrate:latest --knexfile ./dist/database/knexfile.js --env pg && node ./dist/app.js"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER:  postgres 
      POSTGRES_PASSWORD: B3rasm3ntah 
      POSTGRES_DB: lab_d 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5000:80
    restart: always

volumes:
  postgres_data:
    driver: local 
